package com.test.model.entity;
// Generated Oct 25, 2017 1:03:42 PM by Hibernate Tools 5.2.3.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer id;
	private Deparment deparment;
	private String FName;
	private String LName;

	public Employee() {
	}

	public Employee(Deparment deparment, String FName, String LName) {
		this.deparment = deparment;
		this.FName = FName;
		this.LName = LName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Deparment getDeparment() {
		return this.deparment;
	}

	public void setDeparment(Deparment deparment) {
		this.deparment = deparment;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

}
